name: tbls-demo-box
services:
  # tbls:
  #   image: ghcr.io/k1low/tbls
  #   tty: true
  #   depends_on:
  #     mysql:
  #       condition: service_healthy
  #   volumes:
  #     - ./.tbls.yml:/.tbls.yml
  #     - ./docs/dbdoc:/docs/dbdoc
  #   env_file:
  #     - .env
  #   entrypoint: tbls doc mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@mysql:3306/${DATABASE_NAME}

  mysql:
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    image: mysql:8.0
    ports:
      - 127.0.0.1:${DATABASE_PORT:-3306}:3306
    volumes:
            - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    command:
      [
          "--character-set-server=utf8mb4",
          "--collation-server=utf8mb4_unicode_ci",
          "--default-authentication-plugin=mysql_native_password",
      ]
    healthcheck:
      test: "mysqladmin ping -h 127.0.0.1 -u root -p$$DATABASE_PASSWORD"
      timeout: 5s
      interval: 5s
      retries: 10
volumes:
  mysql-data: